name: build-actions

on: [workflow_dispatch, push]

permissions:
  contents: write

jobs:
  build:
    uses: "./.github/workflows/build.yml"

  clean:
    uses: "./.github/workflows/clean.yml"
    needs: [build]
