name: Compiling

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Compile
      uses: Ruochenfu2011/compilation@v1
      
    - name: Archive Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Artifacts
        path: ./build/libs

    - name: Publish
      uses: Kir-Antipov/mc-publish@v3.3
      with:
         modrinth-id: AANobbMI
         modrinth-token: UE4M9RbW
