name: Publish on GitHub & Modrinth
 
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

env:
  MINECRAFT_VERSION: 1.20.1
  JAVA_VERSION: 17
  VERSION: 1.2.0+1.20.1
  RELEASE_NAME: Armor Statues Companion 1.2.0 for 1.20.1
  MODRINTH_TOKEN: ${{ secrets.PUBLISH_MODRINTH_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.PUBLISH_GITHUB_TOKEN }}           

permissions:
  contents: write

jobs:
  build:
    uses: "./.github/workflows/build.yml"

  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check Environment Variables
        run: env

      - name: Publish (Modrinth/GitHub)
        uses: Kir-Antipov/mc-publish@v3.2
        with:
          modrinth-id: UE4M9RbW
          modrinth-token: "${{env.MODRINTH_TOKEN}}"
          
          github-tag: "v${{env.VERSION}}"
          github-token: "${{env.GITHUB_TOKEN}}"

          name: "${{env.RELEASE_NAME}}"                             
          version: "${{env.VERSION}}"
          version-type: release
          changelog-file: CHANGELOG.md

          loaders: fabric
          game-versions: "${{env.MINECRAFT_VERSION}}"
          java: "${{env.JAVA_VERSION}}"
